
logging:
  level:
    root: DEBUG

server:
  context-path: /grisbiweb

spring:
  application:
    name: grisbi-web
  jackson:
    serialization:
      indent-output: true
      
grisbiweb:
  fileuri: classpath:account.gsb