//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:36:53 PM CET 
//


package grisbiweb.server.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Mailc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Rem" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Telc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Faxc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Nac" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Web" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Mail" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Tel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Adr" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BIC" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Co" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Na" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Nb" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Bank")
public class BankXml {

    @XmlAttribute(name = "Mailc", required = true)
    protected String mailc;
    @XmlAttribute(name = "Rem", required = true)
    protected String rem;
    @XmlAttribute(name = "Telc", required = true)
    protected String telc;
    @XmlAttribute(name = "Faxc", required = true)
    protected String faxc;
    @XmlAttribute(name = "Nac", required = true)
    protected String nac;
    @XmlAttribute(name = "Web", required = true)
    protected String web;
    @XmlAttribute(name = "Mail", required = true)
    protected String mail;
    @XmlAttribute(name = "Tel", required = true)
    protected String tel;
    @XmlAttribute(name = "Adr", required = true)
    protected String adr;
    @XmlAttribute(name = "BIC", required = true)
    protected String bic;
    @XmlAttribute(name = "Co", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String co;
    @XmlAttribute(name = "Na", required = true)
    protected String na;
    @XmlAttribute(name = "Nb", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String nb;

    /**
     * Gets the value of the mailc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailc() {
        return mailc;
    }

    /**
     * Sets the value of the mailc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailc(String value) {
        this.mailc = value;
    }

    /**
     * Gets the value of the rem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRem() {
        return rem;
    }

    /**
     * Sets the value of the rem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRem(String value) {
        this.rem = value;
    }

    /**
     * Gets the value of the telc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelc() {
        return telc;
    }

    /**
     * Sets the value of the telc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelc(String value) {
        this.telc = value;
    }

    /**
     * Gets the value of the faxc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxc() {
        return faxc;
    }

    /**
     * Sets the value of the faxc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxc(String value) {
        this.faxc = value;
    }

    /**
     * Gets the value of the nac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNac() {
        return nac;
    }

    /**
     * Sets the value of the nac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNac(String value) {
        this.nac = value;
    }

    /**
     * Gets the value of the web property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeb() {
        return web;
    }

    /**
     * Sets the value of the web property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeb(String value) {
        this.web = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the tel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTel() {
        return tel;
    }

    /**
     * Sets the value of the tel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTel(String value) {
        this.tel = value;
    }

    /**
     * Gets the value of the adr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdr() {
        return adr;
    }

    /**
     * Sets the value of the adr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr(String value) {
        this.adr = value;
    }

    /**
     * Gets the value of the bic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIC() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIC(String value) {
        this.bic = value;
    }

    /**
     * Gets the value of the co property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCo() {
        return co;
    }

    /**
     * Sets the value of the co property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCo(String value) {
        this.co = value;
    }

    /**
     * Gets the value of the na property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNa() {
        return na;
    }

    /**
     * Sets the value of the na property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNa(String value) {
        this.na = value;
    }

    /**
     * Gets the value of the nb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNb() {
        return nb;
    }

    /**
     * Sets the value of the nb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNb(String value) {
        this.nb = value;
    }

}
