//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:36:53 PM CET 
//


package grisbiweb.server.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Background_split_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Couleur_jour_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_archive_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_split_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Selection_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_color_1_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_archive_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Calendar_entry_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Text_color_0_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_color_0_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_color_0_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_color_0_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Selection_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Text_color_0_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Calendar_entry_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_scheduled_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Selection_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_color_1_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_archive_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Text_color_1_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Text_color_1_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Couleur_jour_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Text_color_0_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Couleur_jour_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_scheduled_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Calendar_entry_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_scheduled_blue" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_split_green" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Text_color_1_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Background_color_1_red" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Color")
public class ColorXml {

    @XmlAttribute(name = "Background_split_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundSplitBlue;
    @XmlAttribute(name = "Couleur_jour_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String couleurJourGreen;
    @XmlAttribute(name = "Background_archive_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundArchiveGreen;
    @XmlAttribute(name = "Background_split_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundSplitRed;
    @XmlAttribute(name = "Selection_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String selectionBlue;
    @XmlAttribute(name = "Background_color_1_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundColor1Green;
    @XmlAttribute(name = "Background_archive_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundArchiveBlue;
    @XmlAttribute(name = "Calendar_entry_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String calendarEntryBlue;
    @XmlAttribute(name = "Text_color_0_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String textColor0Red;
    @XmlAttribute(name = "Background_color_0_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundColor0Green;
    @XmlAttribute(name = "Background_color_0_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundColor0Red;
    @XmlAttribute(name = "Background_color_0_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundColor0Blue;
    @XmlAttribute(name = "Selection_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String selectionRed;
    @XmlAttribute(name = "Text_color_0_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String textColor0Blue;
    @XmlAttribute(name = "Calendar_entry_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String calendarEntryRed;
    @XmlAttribute(name = "Background_scheduled_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundScheduledGreen;
    @XmlAttribute(name = "Selection_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String selectionGreen;
    @XmlAttribute(name = "Background_color_1_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundColor1Blue;
    @XmlAttribute(name = "Background_archive_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundArchiveRed;
    @XmlAttribute(name = "Text_color_1_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String textColor1Green;
    @XmlAttribute(name = "Text_color_1_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String textColor1Blue;
    @XmlAttribute(name = "Couleur_jour_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String couleurJourBlue;
    @XmlAttribute(name = "Text_color_0_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String textColor0Green;
    @XmlAttribute(name = "Couleur_jour_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String couleurJourRed;
    @XmlAttribute(name = "Background_scheduled_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundScheduledRed;
    @XmlAttribute(name = "Calendar_entry_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String calendarEntryGreen;
    @XmlAttribute(name = "Background_scheduled_blue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundScheduledBlue;
    @XmlAttribute(name = "Background_split_green", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundSplitGreen;
    @XmlAttribute(name = "Text_color_1_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String textColor1Red;
    @XmlAttribute(name = "Background_color_1_red", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String backgroundColor1Red;

    /**
     * Gets the value of the backgroundSplitBlue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundSplitBlue() {
        return backgroundSplitBlue;
    }

    /**
     * Sets the value of the backgroundSplitBlue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundSplitBlue(String value) {
        this.backgroundSplitBlue = value;
    }

    /**
     * Gets the value of the couleurJourGreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouleurJourGreen() {
        return couleurJourGreen;
    }

    /**
     * Sets the value of the couleurJourGreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouleurJourGreen(String value) {
        this.couleurJourGreen = value;
    }

    /**
     * Gets the value of the backgroundArchiveGreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundArchiveGreen() {
        return backgroundArchiveGreen;
    }

    /**
     * Sets the value of the backgroundArchiveGreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundArchiveGreen(String value) {
        this.backgroundArchiveGreen = value;
    }

    /**
     * Gets the value of the backgroundSplitRed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundSplitRed() {
        return backgroundSplitRed;
    }

    /**
     * Sets the value of the backgroundSplitRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundSplitRed(String value) {
        this.backgroundSplitRed = value;
    }

    /**
     * Gets the value of the selectionBlue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectionBlue() {
        return selectionBlue;
    }

    /**
     * Sets the value of the selectionBlue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectionBlue(String value) {
        this.selectionBlue = value;
    }

    /**
     * Gets the value of the backgroundColor1Green property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor1Green() {
        return backgroundColor1Green;
    }

    /**
     * Sets the value of the backgroundColor1Green property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor1Green(String value) {
        this.backgroundColor1Green = value;
    }

    /**
     * Gets the value of the backgroundArchiveBlue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundArchiveBlue() {
        return backgroundArchiveBlue;
    }

    /**
     * Sets the value of the backgroundArchiveBlue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundArchiveBlue(String value) {
        this.backgroundArchiveBlue = value;
    }

    /**
     * Gets the value of the calendarEntryBlue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalendarEntryBlue() {
        return calendarEntryBlue;
    }

    /**
     * Sets the value of the calendarEntryBlue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalendarEntryBlue(String value) {
        this.calendarEntryBlue = value;
    }

    /**
     * Gets the value of the textColor0Red property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColor0Red() {
        return textColor0Red;
    }

    /**
     * Sets the value of the textColor0Red property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColor0Red(String value) {
        this.textColor0Red = value;
    }

    /**
     * Gets the value of the backgroundColor0Green property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor0Green() {
        return backgroundColor0Green;
    }

    /**
     * Sets the value of the backgroundColor0Green property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor0Green(String value) {
        this.backgroundColor0Green = value;
    }

    /**
     * Gets the value of the backgroundColor0Red property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor0Red() {
        return backgroundColor0Red;
    }

    /**
     * Sets the value of the backgroundColor0Red property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor0Red(String value) {
        this.backgroundColor0Red = value;
    }

    /**
     * Gets the value of the backgroundColor0Blue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor0Blue() {
        return backgroundColor0Blue;
    }

    /**
     * Sets the value of the backgroundColor0Blue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor0Blue(String value) {
        this.backgroundColor0Blue = value;
    }

    /**
     * Gets the value of the selectionRed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectionRed() {
        return selectionRed;
    }

    /**
     * Sets the value of the selectionRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectionRed(String value) {
        this.selectionRed = value;
    }

    /**
     * Gets the value of the textColor0Blue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColor0Blue() {
        return textColor0Blue;
    }

    /**
     * Sets the value of the textColor0Blue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColor0Blue(String value) {
        this.textColor0Blue = value;
    }

    /**
     * Gets the value of the calendarEntryRed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalendarEntryRed() {
        return calendarEntryRed;
    }

    /**
     * Sets the value of the calendarEntryRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalendarEntryRed(String value) {
        this.calendarEntryRed = value;
    }

    /**
     * Gets the value of the backgroundScheduledGreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundScheduledGreen() {
        return backgroundScheduledGreen;
    }

    /**
     * Sets the value of the backgroundScheduledGreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundScheduledGreen(String value) {
        this.backgroundScheduledGreen = value;
    }

    /**
     * Gets the value of the selectionGreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectionGreen() {
        return selectionGreen;
    }

    /**
     * Sets the value of the selectionGreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectionGreen(String value) {
        this.selectionGreen = value;
    }

    /**
     * Gets the value of the backgroundColor1Blue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor1Blue() {
        return backgroundColor1Blue;
    }

    /**
     * Sets the value of the backgroundColor1Blue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor1Blue(String value) {
        this.backgroundColor1Blue = value;
    }

    /**
     * Gets the value of the backgroundArchiveRed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundArchiveRed() {
        return backgroundArchiveRed;
    }

    /**
     * Sets the value of the backgroundArchiveRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundArchiveRed(String value) {
        this.backgroundArchiveRed = value;
    }

    /**
     * Gets the value of the textColor1Green property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColor1Green() {
        return textColor1Green;
    }

    /**
     * Sets the value of the textColor1Green property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColor1Green(String value) {
        this.textColor1Green = value;
    }

    /**
     * Gets the value of the textColor1Blue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColor1Blue() {
        return textColor1Blue;
    }

    /**
     * Sets the value of the textColor1Blue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColor1Blue(String value) {
        this.textColor1Blue = value;
    }

    /**
     * Gets the value of the couleurJourBlue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouleurJourBlue() {
        return couleurJourBlue;
    }

    /**
     * Sets the value of the couleurJourBlue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouleurJourBlue(String value) {
        this.couleurJourBlue = value;
    }

    /**
     * Gets the value of the textColor0Green property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColor0Green() {
        return textColor0Green;
    }

    /**
     * Sets the value of the textColor0Green property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColor0Green(String value) {
        this.textColor0Green = value;
    }

    /**
     * Gets the value of the couleurJourRed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouleurJourRed() {
        return couleurJourRed;
    }

    /**
     * Sets the value of the couleurJourRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouleurJourRed(String value) {
        this.couleurJourRed = value;
    }

    /**
     * Gets the value of the backgroundScheduledRed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundScheduledRed() {
        return backgroundScheduledRed;
    }

    /**
     * Sets the value of the backgroundScheduledRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundScheduledRed(String value) {
        this.backgroundScheduledRed = value;
    }

    /**
     * Gets the value of the calendarEntryGreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalendarEntryGreen() {
        return calendarEntryGreen;
    }

    /**
     * Sets the value of the calendarEntryGreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalendarEntryGreen(String value) {
        this.calendarEntryGreen = value;
    }

    /**
     * Gets the value of the backgroundScheduledBlue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundScheduledBlue() {
        return backgroundScheduledBlue;
    }

    /**
     * Sets the value of the backgroundScheduledBlue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundScheduledBlue(String value) {
        this.backgroundScheduledBlue = value;
    }

    /**
     * Gets the value of the backgroundSplitGreen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundSplitGreen() {
        return backgroundSplitGreen;
    }

    /**
     * Sets the value of the backgroundSplitGreen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundSplitGreen(String value) {
        this.backgroundSplitGreen = value;
    }

    /**
     * Gets the value of the textColor1Red property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColor1Red() {
        return textColor1Red;
    }

    /**
     * Sets the value of the textColor1Red property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColor1Red(String value) {
        this.textColor1Red = value;
    }

    /**
     * Gets the value of the backgroundColor1Red property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor1Red() {
        return backgroundColor1Red;
    }

    /**
     * Sets the value of the backgroundColor1Red property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor1Red(String value) {
        this.backgroundColor1Red = value;
    }

}
