//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:36:53 PM CET 
//


package grisbiweb.server.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Add_archive_in_total_balance" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Metatree_sort_transactions" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="CSV_skipped_lines" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="CSV_separator" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Automatic_amount_separator" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Combofix_force_category" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Combofix_force_payee" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Combofix_enter_select_completion" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Combofix_case_sensitive" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Combofix_max_item" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Combofix_mixed_sort" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Scheduler_column_width" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Transaction_column_width" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Remind_form_per_account" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Three_lines_showed" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Two_lines_showed" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="One_line_showed" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Transactions_view" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Remind_display_per_account" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Use_logo" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Import_fyear_by_value_date" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Import_categorie_for_payee" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Import_fusion_transactions" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Import_extract_number_for_check" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Import_interval_search" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Scheduler_custom_menu" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Scheduler_custom_number" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Scheduler_view" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Budget_list_currency_number" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Category_list_currency_number" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Party_list_currency_number" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Second_general_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="General_address" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="File_title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Archive_file" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Crypt_file" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Grisbi_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="File_version" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "General")
public class GeneralXml {

    @XmlAttribute(name = "Add_archive_in_total_balance", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String addArchiveInTotalBalance;
    @XmlAttribute(name = "Metatree_sort_transactions", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String metatreeSortTransactions;
    @XmlAttribute(name = "CSV_skipped_lines", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String csvSkippedLines;
    @XmlAttribute(name = "CSV_separator", required = true)
    protected String csvSeparator;
    @XmlAttribute(name = "Automatic_amount_separator", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String automaticAmountSeparator;
    @XmlAttribute(name = "Combofix_force_category", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String combofixForceCategory;
    @XmlAttribute(name = "Combofix_force_payee", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String combofixForcePayee;
    @XmlAttribute(name = "Combofix_enter_select_completion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String combofixEnterSelectCompletion;
    @XmlAttribute(name = "Combofix_case_sensitive", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String combofixCaseSensitive;
    @XmlAttribute(name = "Combofix_max_item", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String combofixMaxItem;
    @XmlAttribute(name = "Combofix_mixed_sort", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String combofixMixedSort;
    @XmlAttribute(name = "Scheduler_column_width", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String schedulerColumnWidth;
    @XmlAttribute(name = "Transaction_column_width", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String transactionColumnWidth;
    @XmlAttribute(name = "Remind_form_per_account", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String remindFormPerAccount;
    @XmlAttribute(name = "Three_lines_showed", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String threeLinesShowed;
    @XmlAttribute(name = "Two_lines_showed", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String twoLinesShowed;
    @XmlAttribute(name = "One_line_showed", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String oneLineShowed;
    @XmlAttribute(name = "Transactions_view", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String transactionsView;
    @XmlAttribute(name = "Remind_display_per_account", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String remindDisplayPerAccount;
    @XmlAttribute(name = "Use_logo", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String useLogo;
    @XmlAttribute(name = "Import_fyear_by_value_date", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String importFyearByValueDate;
    @XmlAttribute(name = "Import_categorie_for_payee", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String importCategorieForPayee;
    @XmlAttribute(name = "Import_fusion_transactions", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String importFusionTransactions;
    @XmlAttribute(name = "Import_extract_number_for_check", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String importExtractNumberForCheck;
    @XmlAttribute(name = "Import_interval_search", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String importIntervalSearch;
    @XmlAttribute(name = "Scheduler_custom_menu", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String schedulerCustomMenu;
    @XmlAttribute(name = "Scheduler_custom_number", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String schedulerCustomNumber;
    @XmlAttribute(name = "Scheduler_view", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String schedulerView;
    @XmlAttribute(name = "Budget_list_currency_number", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String budgetListCurrencyNumber;
    @XmlAttribute(name = "Category_list_currency_number", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String categoryListCurrencyNumber;
    @XmlAttribute(name = "Party_list_currency_number", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String partyListCurrencyNumber;
    @XmlAttribute(name = "Second_general_address", required = true)
    protected String secondGeneralAddress;
    @XmlAttribute(name = "General_address", required = true)
    protected String generalAddress;
    @XmlAttribute(name = "File_title", required = true)
    protected String fileTitle;
    @XmlAttribute(name = "Archive_file", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String archiveFile;
    @XmlAttribute(name = "Crypt_file", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String cryptFile;
    @XmlAttribute(name = "Grisbi_version", required = true)
    protected String grisbiVersion;
    @XmlAttribute(name = "File_version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String fileVersion;

    /**
     * Gets the value of the addArchiveInTotalBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddArchiveInTotalBalance() {
        return addArchiveInTotalBalance;
    }

    /**
     * Sets the value of the addArchiveInTotalBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddArchiveInTotalBalance(String value) {
        this.addArchiveInTotalBalance = value;
    }

    /**
     * Gets the value of the metatreeSortTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetatreeSortTransactions() {
        return metatreeSortTransactions;
    }

    /**
     * Sets the value of the metatreeSortTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetatreeSortTransactions(String value) {
        this.metatreeSortTransactions = value;
    }

    /**
     * Gets the value of the csvSkippedLines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSVSkippedLines() {
        return csvSkippedLines;
    }

    /**
     * Sets the value of the csvSkippedLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSVSkippedLines(String value) {
        this.csvSkippedLines = value;
    }

    /**
     * Gets the value of the csvSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSVSeparator() {
        return csvSeparator;
    }

    /**
     * Sets the value of the csvSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSVSeparator(String value) {
        this.csvSeparator = value;
    }

    /**
     * Gets the value of the automaticAmountSeparator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutomaticAmountSeparator() {
        return automaticAmountSeparator;
    }

    /**
     * Sets the value of the automaticAmountSeparator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomaticAmountSeparator(String value) {
        this.automaticAmountSeparator = value;
    }

    /**
     * Gets the value of the combofixForceCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombofixForceCategory() {
        return combofixForceCategory;
    }

    /**
     * Sets the value of the combofixForceCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombofixForceCategory(String value) {
        this.combofixForceCategory = value;
    }

    /**
     * Gets the value of the combofixForcePayee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombofixForcePayee() {
        return combofixForcePayee;
    }

    /**
     * Sets the value of the combofixForcePayee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombofixForcePayee(String value) {
        this.combofixForcePayee = value;
    }

    /**
     * Gets the value of the combofixEnterSelectCompletion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombofixEnterSelectCompletion() {
        return combofixEnterSelectCompletion;
    }

    /**
     * Sets the value of the combofixEnterSelectCompletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombofixEnterSelectCompletion(String value) {
        this.combofixEnterSelectCompletion = value;
    }

    /**
     * Gets the value of the combofixCaseSensitive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombofixCaseSensitive() {
        return combofixCaseSensitive;
    }

    /**
     * Sets the value of the combofixCaseSensitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombofixCaseSensitive(String value) {
        this.combofixCaseSensitive = value;
    }

    /**
     * Gets the value of the combofixMaxItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombofixMaxItem() {
        return combofixMaxItem;
    }

    /**
     * Sets the value of the combofixMaxItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombofixMaxItem(String value) {
        this.combofixMaxItem = value;
    }

    /**
     * Gets the value of the combofixMixedSort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombofixMixedSort() {
        return combofixMixedSort;
    }

    /**
     * Sets the value of the combofixMixedSort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombofixMixedSort(String value) {
        this.combofixMixedSort = value;
    }

    /**
     * Gets the value of the schedulerColumnWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerColumnWidth() {
        return schedulerColumnWidth;
    }

    /**
     * Sets the value of the schedulerColumnWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerColumnWidth(String value) {
        this.schedulerColumnWidth = value;
    }

    /**
     * Gets the value of the transactionColumnWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionColumnWidth() {
        return transactionColumnWidth;
    }

    /**
     * Sets the value of the transactionColumnWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionColumnWidth(String value) {
        this.transactionColumnWidth = value;
    }

    /**
     * Gets the value of the remindFormPerAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemindFormPerAccount() {
        return remindFormPerAccount;
    }

    /**
     * Sets the value of the remindFormPerAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemindFormPerAccount(String value) {
        this.remindFormPerAccount = value;
    }

    /**
     * Gets the value of the threeLinesShowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreeLinesShowed() {
        return threeLinesShowed;
    }

    /**
     * Sets the value of the threeLinesShowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreeLinesShowed(String value) {
        this.threeLinesShowed = value;
    }

    /**
     * Gets the value of the twoLinesShowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwoLinesShowed() {
        return twoLinesShowed;
    }

    /**
     * Sets the value of the twoLinesShowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwoLinesShowed(String value) {
        this.twoLinesShowed = value;
    }

    /**
     * Gets the value of the oneLineShowed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOneLineShowed() {
        return oneLineShowed;
    }

    /**
     * Sets the value of the oneLineShowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOneLineShowed(String value) {
        this.oneLineShowed = value;
    }

    /**
     * Gets the value of the transactionsView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionsView() {
        return transactionsView;
    }

    /**
     * Sets the value of the transactionsView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionsView(String value) {
        this.transactionsView = value;
    }

    /**
     * Gets the value of the remindDisplayPerAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemindDisplayPerAccount() {
        return remindDisplayPerAccount;
    }

    /**
     * Sets the value of the remindDisplayPerAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemindDisplayPerAccount(String value) {
        this.remindDisplayPerAccount = value;
    }

    /**
     * Gets the value of the useLogo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseLogo() {
        return useLogo;
    }

    /**
     * Sets the value of the useLogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseLogo(String value) {
        this.useLogo = value;
    }

    /**
     * Gets the value of the importFyearByValueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportFyearByValueDate() {
        return importFyearByValueDate;
    }

    /**
     * Sets the value of the importFyearByValueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportFyearByValueDate(String value) {
        this.importFyearByValueDate = value;
    }

    /**
     * Gets the value of the importCategorieForPayee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportCategorieForPayee() {
        return importCategorieForPayee;
    }

    /**
     * Sets the value of the importCategorieForPayee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportCategorieForPayee(String value) {
        this.importCategorieForPayee = value;
    }

    /**
     * Gets the value of the importFusionTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportFusionTransactions() {
        return importFusionTransactions;
    }

    /**
     * Sets the value of the importFusionTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportFusionTransactions(String value) {
        this.importFusionTransactions = value;
    }

    /**
     * Gets the value of the importExtractNumberForCheck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportExtractNumberForCheck() {
        return importExtractNumberForCheck;
    }

    /**
     * Sets the value of the importExtractNumberForCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportExtractNumberForCheck(String value) {
        this.importExtractNumberForCheck = value;
    }

    /**
     * Gets the value of the importIntervalSearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportIntervalSearch() {
        return importIntervalSearch;
    }

    /**
     * Sets the value of the importIntervalSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportIntervalSearch(String value) {
        this.importIntervalSearch = value;
    }

    /**
     * Gets the value of the schedulerCustomMenu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerCustomMenu() {
        return schedulerCustomMenu;
    }

    /**
     * Sets the value of the schedulerCustomMenu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerCustomMenu(String value) {
        this.schedulerCustomMenu = value;
    }

    /**
     * Gets the value of the schedulerCustomNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerCustomNumber() {
        return schedulerCustomNumber;
    }

    /**
     * Sets the value of the schedulerCustomNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerCustomNumber(String value) {
        this.schedulerCustomNumber = value;
    }

    /**
     * Gets the value of the schedulerView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerView() {
        return schedulerView;
    }

    /**
     * Sets the value of the schedulerView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerView(String value) {
        this.schedulerView = value;
    }

    /**
     * Gets the value of the budgetListCurrencyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBudgetListCurrencyNumber() {
        return budgetListCurrencyNumber;
    }

    /**
     * Sets the value of the budgetListCurrencyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBudgetListCurrencyNumber(String value) {
        this.budgetListCurrencyNumber = value;
    }

    /**
     * Gets the value of the categoryListCurrencyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategoryListCurrencyNumber() {
        return categoryListCurrencyNumber;
    }

    /**
     * Sets the value of the categoryListCurrencyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategoryListCurrencyNumber(String value) {
        this.categoryListCurrencyNumber = value;
    }

    /**
     * Gets the value of the partyListCurrencyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyListCurrencyNumber() {
        return partyListCurrencyNumber;
    }

    /**
     * Sets the value of the partyListCurrencyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyListCurrencyNumber(String value) {
        this.partyListCurrencyNumber = value;
    }

    /**
     * Gets the value of the secondGeneralAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondGeneralAddress() {
        return secondGeneralAddress;
    }

    /**
     * Sets the value of the secondGeneralAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondGeneralAddress(String value) {
        this.secondGeneralAddress = value;
    }

    /**
     * Gets the value of the generalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneralAddress() {
        return generalAddress;
    }

    /**
     * Sets the value of the generalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneralAddress(String value) {
        this.generalAddress = value;
    }

    /**
     * Gets the value of the fileTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileTitle() {
        return fileTitle;
    }

    /**
     * Sets the value of the fileTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileTitle(String value) {
        this.fileTitle = value;
    }

    /**
     * Gets the value of the archiveFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchiveFile() {
        return archiveFile;
    }

    /**
     * Sets the value of the archiveFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchiveFile(String value) {
        this.archiveFile = value;
    }

    /**
     * Gets the value of the cryptFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCryptFile() {
        return cryptFile;
    }

    /**
     * Sets the value of the cryptFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCryptFile(String value) {
        this.cryptFile = value;
    }

    /**
     * Gets the value of the grisbiVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrisbiVersion() {
        return grisbiVersion;
    }

    /**
     * Sets the value of the grisbiVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrisbiVersion(String value) {
        this.grisbiVersion = value;
    }

    /**
     * Gets the value of the fileVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileVersion() {
        return fileVersion;
    }

    /**
     * Sets the value of the fileVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileVersion(String value) {
        this.fileVersion = value;
    }

}
