//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:36:53 PM CET 
//


package grisbiweb.server.xml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}General"/>
 *         &lt;element ref="{}Color"/>
 *         &lt;element ref="{}Print"/>
 *         &lt;element ref="{}Currency" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Account" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Payment" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Transaction" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Party" maxOccurs="unbounded"/>
 *         &lt;group ref="{}GroupCategories" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Bank" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Reconcile" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Logo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "general",
    "color",
    "print",
    "currency",
    "account",
    "payment",
    "transaction",
    "party",
    "groupCategories",
    "bank",
    "reconcile",
    "logo"
})
@XmlRootElement(name = "Grisbi")
public class GrisbiXml {

    @XmlElement(name = "General", required = true)
    protected GeneralXml general;
    @XmlElement(name = "Color", required = true)
    protected ColorXml color;
    @XmlElement(name = "Print", required = true)
    protected PrintXml print;
    @XmlElement(name = "Currency", required = true)
    protected List<CurrencyXml> currency;
    @XmlElement(name = "Account", required = true)
    protected List<AccountXml> account;
    @XmlElement(name = "Payment", required = true)
    protected List<PaymentXml> payment;
    @XmlElement(name = "Transaction", required = true)
    protected List<TransactionXml> transaction;
    @XmlElement(name = "Party", required = true)
    protected List<PartyXml> party;
    @XmlElements({
        @XmlElement(name = "Category", required = true, type = CategoryXml.class),
        @XmlElement(name = "Sub_category", required = true, type = SubCategoryXml.class)
    })
    protected List<Object> groupCategories;
    @XmlElement(name = "Bank", required = true)
    protected List<BankXml> bank;
    @XmlElement(name = "Reconcile", required = true)
    protected List<ReconcileXml> reconcile;
    @XmlElement(name = "Logo", required = true)
    protected LogoXml logo;

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralXml }
     *     
     */
    public GeneralXml getGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralXml }
     *     
     */
    public void setGeneral(GeneralXml value) {
        this.general = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link ColorXml }
     *     
     */
    public ColorXml getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorXml }
     *     
     */
    public void setColor(ColorXml value) {
        this.color = value;
    }

    /**
     * Gets the value of the print property.
     * 
     * @return
     *     possible object is
     *     {@link PrintXml }
     *     
     */
    public PrintXml getPrint() {
        return print;
    }

    /**
     * Sets the value of the print property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintXml }
     *     
     */
    public void setPrint(PrintXml value) {
        this.print = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the currency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCurrency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CurrencyXml }
     * 
     * 
     */
    public List<CurrencyXml> getCurrency() {
        if (currency == null) {
            currency = new ArrayList<CurrencyXml>();
        }
        return this.currency;
    }

    /**
     * Gets the value of the account property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the account property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccountXml }
     * 
     * 
     */
    public List<AccountXml> getAccount() {
        if (account == null) {
            account = new ArrayList<AccountXml>();
        }
        return this.account;
    }

    /**
     * Gets the value of the payment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the payment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPayment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentXml }
     * 
     * 
     */
    public List<PaymentXml> getPayment() {
        if (payment == null) {
            payment = new ArrayList<PaymentXml>();
        }
        return this.payment;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransactionXml }
     * 
     * 
     */
    public List<TransactionXml> getTransaction() {
        if (transaction == null) {
            transaction = new ArrayList<TransactionXml>();
        }
        return this.transaction;
    }

    /**
     * Gets the value of the party property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the party property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyXml }
     * 
     * 
     */
    public List<PartyXml> getParty() {
        if (party == null) {
            party = new ArrayList<PartyXml>();
        }
        return this.party;
    }

    /**
     * Gets the value of the groupCategories property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupCategories property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupCategories().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryXml }
     * {@link SubCategoryXml }
     * 
     * 
     */
    public List<Object> getGroupCategories() {
        if (groupCategories == null) {
            groupCategories = new ArrayList<Object>();
        }
        return this.groupCategories;
    }

    /**
     * Gets the value of the bank property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bank property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBank().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankXml }
     * 
     * 
     */
    public List<BankXml> getBank() {
        if (bank == null) {
            bank = new ArrayList<BankXml>();
        }
        return this.bank;
    }

    /**
     * Gets the value of the reconcile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reconcile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReconcile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReconcileXml }
     * 
     * 
     */
    public List<ReconcileXml> getReconcile() {
        if (reconcile == null) {
            reconcile = new ArrayList<ReconcileXml>();
        }
        return this.reconcile;
    }

    /**
     * Gets the value of the logo property.
     * 
     * @return
     *     possible object is
     *     {@link LogoXml }
     *     
     */
    public LogoXml getLogo() {
        return logo;
    }

    /**
     * Sets the value of the logo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogoXml }
     *     
     */
    public void setLogo(LogoXml value) {
        this.logo = value;
    }

}
