//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:36:53 PM CET 
//

package grisbiweb.server.xml.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the fr.tetrias.grisbiweb.xml.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: fr.tetrias.grisbiweb.xml.model
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link GrisbiXml }
	 * 
	 */
	public GrisbiXml createGrisbi() {
		return new GrisbiXml();
	}

	/**
	 * Create an instance of {@link GeneralXml }
	 * 
	 */
	public GeneralXml createGeneral() {
		return new GeneralXml();
	}

	/**
	 * Create an instance of {@link ColorXml }
	 * 
	 */
	public ColorXml createColor() {
		return new ColorXml();
	}

	/**
	 * Create an instance of {@link PrintXml }
	 * 
	 */
	public PrintXml createPrint() {
		return new PrintXml();
	}

	/**
	 * Create an instance of {@link CurrencyXml }
	 * 
	 */
	public CurrencyXml createCurrency() {
		return new CurrencyXml();
	}

	/**
	 * Create an instance of {@link AccountXml }
	 * 
	 */
	public AccountXml createAccount() {
		return new AccountXml();
	}

	/**
	 * Create an instance of {@link PaymentXml }
	 * 
	 */
	public PaymentXml createPayment() {
		return new PaymentXml();
	}

	/**
	 * Create an instance of {@link TransactionXml }
	 * 
	 */
	public TransactionXml createTransaction() {
		return new TransactionXml();
	}

	/**
	 * Create an instance of {@link PartyXml }
	 * 
	 */
	public PartyXml createParty() {
		return new PartyXml();
	}

	/**
	 * Create an instance of {@link CategoryXml }
	 * 
	 */
	public CategoryXml createCategory() {
		return new CategoryXml();
	}

	/**
	 * Create an instance of {@link SubCategoryXml }
	 * 
	 */
	public SubCategoryXml createSubCategory() {
		return new SubCategoryXml();
	}

	/**
	 * Create an instance of {@link BankXml }
	 * 
	 */
	public BankXml createBank() {
		return new BankXml();
	}

	/**
	 * Create an instance of {@link ReconcileXml }
	 * 
	 */
	public ReconcileXml createReconcile() {
		return new ReconcileXml();
	}

	/**
	 * Create an instance of {@link LogoXml }
	 * 
	 */
	public LogoXml createLogo() {
		return new LogoXml();
	}

}
