//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:36:53 PM CET 
//


package grisbiweb.server.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Font_transactions" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Report_font_title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Report_font_transactions" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Draw_archives" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Draw_title" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Draw_columns_name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Draw_column" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Draw_lines" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Draw_dates_are_value_dates" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Draw_interval_dates" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Font_title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Draw_background" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Print")
public class PrintXml {

    @XmlAttribute(name = "Font_transactions", required = true)
    protected String fontTransactions;
    @XmlAttribute(name = "Report_font_title", required = true)
    protected String reportFontTitle;
    @XmlAttribute(name = "Report_font_transactions", required = true)
    protected String reportFontTransactions;
    @XmlAttribute(name = "Draw_archives", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String drawArchives;
    @XmlAttribute(name = "Draw_title", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String drawTitle;
    @XmlAttribute(name = "Draw_columns_name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String drawColumnsName;
    @XmlAttribute(name = "Draw_column", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String drawColumn;
    @XmlAttribute(name = "Draw_lines", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String drawLines;
    @XmlAttribute(name = "Draw_dates_are_value_dates", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String drawDatesAreValueDates;
    @XmlAttribute(name = "Draw_interval_dates", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String drawIntervalDates;
    @XmlAttribute(name = "Font_title", required = true)
    protected String fontTitle;
    @XmlAttribute(name = "Draw_background", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String drawBackground;

    /**
     * Gets the value of the fontTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontTransactions() {
        return fontTransactions;
    }

    /**
     * Sets the value of the fontTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontTransactions(String value) {
        this.fontTransactions = value;
    }

    /**
     * Gets the value of the reportFontTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportFontTitle() {
        return reportFontTitle;
    }

    /**
     * Sets the value of the reportFontTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportFontTitle(String value) {
        this.reportFontTitle = value;
    }

    /**
     * Gets the value of the reportFontTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportFontTransactions() {
        return reportFontTransactions;
    }

    /**
     * Sets the value of the reportFontTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportFontTransactions(String value) {
        this.reportFontTransactions = value;
    }

    /**
     * Gets the value of the drawArchives property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawArchives() {
        return drawArchives;
    }

    /**
     * Sets the value of the drawArchives property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawArchives(String value) {
        this.drawArchives = value;
    }

    /**
     * Gets the value of the drawTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawTitle() {
        return drawTitle;
    }

    /**
     * Sets the value of the drawTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawTitle(String value) {
        this.drawTitle = value;
    }

    /**
     * Gets the value of the drawColumnsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawColumnsName() {
        return drawColumnsName;
    }

    /**
     * Sets the value of the drawColumnsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawColumnsName(String value) {
        this.drawColumnsName = value;
    }

    /**
     * Gets the value of the drawColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawColumn() {
        return drawColumn;
    }

    /**
     * Sets the value of the drawColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawColumn(String value) {
        this.drawColumn = value;
    }

    /**
     * Gets the value of the drawLines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawLines() {
        return drawLines;
    }

    /**
     * Sets the value of the drawLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawLines(String value) {
        this.drawLines = value;
    }

    /**
     * Gets the value of the drawDatesAreValueDates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawDatesAreValueDates() {
        return drawDatesAreValueDates;
    }

    /**
     * Sets the value of the drawDatesAreValueDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawDatesAreValueDates(String value) {
        this.drawDatesAreValueDates = value;
    }

    /**
     * Gets the value of the drawIntervalDates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawIntervalDates() {
        return drawIntervalDates;
    }

    /**
     * Sets the value of the drawIntervalDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawIntervalDates(String value) {
        this.drawIntervalDates = value;
    }

    /**
     * Gets the value of the fontTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFontTitle() {
        return fontTitle;
    }

    /**
     * Sets the value of the fontTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontTitle(String value) {
        this.fontTitle = value;
    }

    /**
     * Gets the value of the drawBackground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawBackground() {
        return drawBackground;
    }

    /**
     * Sets the value of the drawBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawBackground(String value) {
        this.drawBackground = value;
    }

}
