//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.06 at 02:36:53 PM CET 
//


package grisbiweb.server.xml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Mo" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="0" />
 *       &lt;attribute name="Trt" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="0"/>
 *             &lt;enumeration value="1656"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Ba" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Vo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sbu" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="0" />
 *       &lt;attribute name="Bu" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="0" />
 *       &lt;attribute name="Fi" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="0" />
 *       &lt;attribute name="Re" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Au" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="0" />
 *       &lt;attribute name="Ar" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="0" />
 *       &lt;attribute name="Ma" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="3" />
 *       &lt;attribute name="Pc" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Pn" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="No" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Br" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="0" />
 *       &lt;attribute name="Sca" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Ca" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Pa" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Exf" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="0.0"/>
 *             &lt;enumeration value="0.0000000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Exr" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="0.0"/>
 *             &lt;enumeration value="0.0000000"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Exb" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="0" />
 *       &lt;attribute name="Am" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Cu" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="1" />
 *       &lt;attribute name="Dv" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Dt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Nb" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="Ac" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="0"/>
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="6"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Transaction")
public class TransactionXml {

    @XmlAttribute(name = "Mo", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String mo;
    @XmlAttribute(name = "Trt", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String trt;
    @XmlAttribute(name = "Ba", required = true)
    protected String ba;
    @XmlAttribute(name = "Vo", required = true)
    protected String vo;
    @XmlAttribute(name = "Sbu", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String sbu;
    @XmlAttribute(name = "Bu", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String bu;
    @XmlAttribute(name = "Fi", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String fi;
    @XmlAttribute(name = "Re", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String re;
    @XmlAttribute(name = "Au", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String au;
    @XmlAttribute(name = "Ar", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String ar;
    @XmlAttribute(name = "Ma", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String ma;
    @XmlAttribute(name = "Pc", required = true)
    protected String pc;
    @XmlAttribute(name = "Pn", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pn;
    @XmlAttribute(name = "No", required = true)
    protected String no;
    @XmlAttribute(name = "Br", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String br;
    @XmlAttribute(name = "Sca", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String sca;
    @XmlAttribute(name = "Ca", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String ca;
    @XmlAttribute(name = "Pa", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String pa;
    @XmlAttribute(name = "Exf", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String exf;
    @XmlAttribute(name = "Exr", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String exr;
    @XmlAttribute(name = "Exb", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String exb;
    @XmlAttribute(name = "Am", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String am;
    @XmlAttribute(name = "Cu", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String cu;
    @XmlAttribute(name = "Dv", required = true)
    protected String dv;
    @XmlAttribute(name = "Dt", required = true)
    protected String dt;
    @XmlAttribute(name = "Id", required = true)
    protected String id;
    @XmlAttribute(name = "Nb", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String nb;
    @XmlAttribute(name = "Ac", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ac;

    /**
     * Gets the value of the mo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMo() {
        if (mo == null) {
            return "0";
        } else {
            return mo;
        }
    }

    /**
     * Sets the value of the mo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMo(String value) {
        this.mo = value;
    }

    /**
     * Gets the value of the trt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrt() {
        return trt;
    }

    /**
     * Sets the value of the trt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrt(String value) {
        this.trt = value;
    }

    /**
     * Gets the value of the ba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBa() {
        return ba;
    }

    /**
     * Sets the value of the ba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBa(String value) {
        this.ba = value;
    }

    /**
     * Gets the value of the vo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVo() {
        return vo;
    }

    /**
     * Sets the value of the vo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVo(String value) {
        this.vo = value;
    }

    /**
     * Gets the value of the sbu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSbu() {
        if (sbu == null) {
            return "0";
        } else {
            return sbu;
        }
    }

    /**
     * Sets the value of the sbu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSbu(String value) {
        this.sbu = value;
    }

    /**
     * Gets the value of the bu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBu() {
        if (bu == null) {
            return "0";
        } else {
            return bu;
        }
    }

    /**
     * Sets the value of the bu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBu(String value) {
        this.bu = value;
    }

    /**
     * Gets the value of the fi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFi() {
        if (fi == null) {
            return "0";
        } else {
            return fi;
        }
    }

    /**
     * Sets the value of the fi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFi(String value) {
        this.fi = value;
    }

    /**
     * Gets the value of the re property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRe() {
        return re;
    }

    /**
     * Sets the value of the re property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRe(String value) {
        this.re = value;
    }

    /**
     * Gets the value of the au property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAu() {
        if (au == null) {
            return "0";
        } else {
            return au;
        }
    }

    /**
     * Sets the value of the au property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAu(String value) {
        this.au = value;
    }

    /**
     * Gets the value of the ar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAr() {
        if (ar == null) {
            return "0";
        } else {
            return ar;
        }
    }

    /**
     * Sets the value of the ar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAr(String value) {
        this.ar = value;
    }

    /**
     * Gets the value of the ma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMa() {
        if (ma == null) {
            return "3";
        } else {
            return ma;
        }
    }

    /**
     * Sets the value of the ma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMa(String value) {
        this.ma = value;
    }

    /**
     * Gets the value of the pc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPc() {
        return pc;
    }

    /**
     * Sets the value of the pc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPc(String value) {
        this.pc = value;
    }

    /**
     * Gets the value of the pn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPn() {
        return pn;
    }

    /**
     * Sets the value of the pn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPn(String value) {
        this.pn = value;
    }

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNo(String value) {
        this.no = value;
    }

    /**
     * Gets the value of the br property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBr() {
        if (br == null) {
            return "0";
        } else {
            return br;
        }
    }

    /**
     * Sets the value of the br property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBr(String value) {
        this.br = value;
    }

    /**
     * Gets the value of the sca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSca() {
        return sca;
    }

    /**
     * Sets the value of the sca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSca(String value) {
        this.sca = value;
    }

    /**
     * Gets the value of the ca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCa() {
        return ca;
    }

    /**
     * Sets the value of the ca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCa(String value) {
        this.ca = value;
    }

    /**
     * Gets the value of the pa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPa() {
        return pa;
    }

    /**
     * Sets the value of the pa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPa(String value) {
        this.pa = value;
    }

    /**
     * Gets the value of the exf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExf() {
        return exf;
    }

    /**
     * Sets the value of the exf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExf(String value) {
        this.exf = value;
    }

    /**
     * Gets the value of the exr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExr() {
        return exr;
    }

    /**
     * Sets the value of the exr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExr(String value) {
        this.exr = value;
    }

    /**
     * Gets the value of the exb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExb() {
        if (exb == null) {
            return "0";
        } else {
            return exb;
        }
    }

    /**
     * Sets the value of the exb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExb(String value) {
        this.exb = value;
    }

    /**
     * Gets the value of the am property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAm() {
        return am;
    }

    /**
     * Sets the value of the am property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAm(String value) {
        this.am = value;
    }

    /**
     * Gets the value of the cu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCu() {
        if (cu == null) {
            return "1";
        } else {
            return cu;
        }
    }

    /**
     * Sets the value of the cu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCu(String value) {
        this.cu = value;
    }

    /**
     * Gets the value of the dv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDv() {
        return dv;
    }

    /**
     * Sets the value of the dv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDv(String value) {
        this.dv = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDt() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDt(String value) {
        this.dt = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the nb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNb() {
        return nb;
    }

    /**
     * Sets the value of the nb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNb(String value) {
        this.nb = value;
    }

    /**
     * Gets the value of the ac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAc() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAc(String value) {
        this.ac = value;
    }

}
